package politics

import (
	"math"
)

// Ideology represents a political orientation
type Ideology struct {
	Name       string
	Economy    float64
	Diplomacy  float64
	Government float64
	Society    float64
}

// IdeologicDistance returns the distance of the average of all ideologic properties
func IdeologicDistance(oneIdeology, anotherIdeology Ideology) float64 {
	return math.Sqrt(
		math.Pow(oneIdeology.Economy-anotherIdeology.Economy, 2) + math.Pow(oneIdeology.Diplomacy-anotherIdeology.Diplomacy, 2) + math.Pow(oneIdeology.Government-anotherIdeology.Government, 2) + math.Pow(oneIdeology.Society-anotherIdeology.Society, 2))
}

// Ideologies contains the collection of all known ideologies
var Ideologies = []Ideology{
	{
		Name:       "Anarcho-Communism",
		Economy:    100,
		Diplomacy:  50,
		Government: 100,
		Society:    90,
	},
	{
		Name:       "Libertarian Communism",
		Economy:    100,
		Diplomacy:  70,
		Government: 80,
		Society:    80,
	},
	{
		Name:       "Trotskyism",
		Economy:    100,
		Diplomacy:  100,
		Government: 60,
		Society:    80,
	},
	{
		Name:       "Marxism",
		Economy:    100,
		Diplomacy:  70,
		Government: 40,
		Society:    80,
	},
	{
		Name:       "De Leonism",
		Economy:    100,
		Diplomacy:  30,
		Government: 30,
		Society:    80,
	},
	{
		Name:       "Leninism",
		Economy:    100,
		Diplomacy:  40,
		Government: 20,
		Society:    70,
	},
	{
		Name:       "Stalinism/Maoism",
		Economy:    100,
		Diplomacy:  20,
		Government: 0,
		Society:    60,
	},
	{
		Name:       "Religious Communism",
		Economy:    100,
		Diplomacy:  50,
		Government: 30,
		Society:    30,
	},
	{
		Name:       "State Socialism",
		Economy:    80,
		Diplomacy:  30,
		Government: 30,
		Society:    70,
	},
	{
		Name:       "Theocratic Socialism",
		Economy:    80,
		Diplomacy:  50,
		Government: 30,
		Society:    20,
	},
	{
		Name:       "Religious Socialism",
		Economy:    80,
		Diplomacy:  50,
		Government: 70,
		Society:    20,
	},
	{
		Name:       "Democratic Socialism",
		Economy:    80,
		Diplomacy:  50,
		Government: 50,
		Society:    80,
	},
	{
		Name:       "Revolutionary Socialism",
		Economy:    80,
		Diplomacy:  20,
		Government: 50,
		Society:    70,
	},
	{
		Name:       "Libertarian Socialism",
		Economy:    80,
		Diplomacy:  80,
		Government: 80,
		Society:    80,
	},
	{
		Name:       "Anarcho-Syndicalism",
		Economy:    80,
		Diplomacy:  50,
		Government: 100,
		Society:    80,
	},
	{
		Name:       "Left-Wing Populism",
		Economy:    60,
		Diplomacy:  40,
		Government: 30,
		Society:    70,
	},
	{
		Name:       "Theocratic Distributism",
		Economy:    60,
		Diplomacy:  40,
		Government: 30,
		Society:    20,
	},
	{
		Name:       "Distributism",
		Economy:    60,
		Diplomacy:  50,
		Government: 50,
		Society:    20,
	},
	{
		Name:       "Social Liberalism",
		Economy:    60,
		Diplomacy:  60,
		Government: 60,
		Society:    80,
	},
	{
		Name:       "Christian Democracy",
		Economy:    60,
		Diplomacy:  60,
		Government: 50,
		Society:    30,
	},
	{
		Name:       "Social Democracy",
		Economy:    60,
		Diplomacy:  70,
		Government: 60,
		Society:    80,
	},
	{
		Name:       "Progressivism",
		Economy:    60,
		Diplomacy:  80,
		Government: 60,
		Society:    100,
	},
	{
		Name:       "Anarcho-Mutualism",
		Economy:    60,
		Diplomacy:  50,
		Government: 100,
		Society:    70,
	},
	{
		Name:       "National Totalitarianism",
		Economy:    50,
		Diplomacy:  20,
		Government: 0,
		Society:    50,
	},
	{
		Name:       "Global Totalitarianism",
		Economy:    50,
		Diplomacy:  80,
		Government: 0,
		Society:    50,
	},
	{
		Name:       "Technocracy",
		Economy:    60,
		Diplomacy:  60,
		Government: 20,
		Society:    70,
	},
	{
		Name:       "Centrist",
		Economy:    50,
		Diplomacy:  50,
		Government: 50,
		Society:    50,
	},
	{
		Name:       "Liberalism",
		Economy:    50,
		Diplomacy:  60,
		Government: 60,
		Society:    60,
	},
	{
		Name:       "Religious Anarchism",
		Economy:    50,
		Diplomacy:  50,
		Government: 100,
		Society:    20,
	},
	{
		Name:       "Right-Wing Populism",
		Economy:    40,
		Diplomacy:  30,
		Government: 30,
		Society:    30,
	},
	{
		Name:       "Moderate Conservatism",
		Economy:    40,
		Diplomacy:  40,
		Government: 50,
		Society:    30,
	},
	{
		Name:       "Reactionary",
		Economy:    40,
		Diplomacy:  40,
		Government: 40,
		Society:    10,
	},
	{
		Name:       "Social Libertarianism",
		Economy:    60,
		Diplomacy:  70,
		Government: 80,
		Society:    70,
	},
	{
		Name:       "Libertarianism",
		Economy:    40,
		Diplomacy:  60,
		Government: 80,
		Society:    60,
	},
	{
		Name:       "Anarcho-Egoism",
		Economy:    40,
		Diplomacy:  50,
		Government: 100,
		Society:    50,
	},
	{
		Name:       "Nazism",
		Economy:    40,
		Diplomacy:  0,
		Government: 0,
		Society:    5,
	},
	{
		Name:       "Autocracy",
		Economy:    50,
		Diplomacy:  20,
		Government: 20,
		Society:    50,
	},
	{
		Name:       "Fascism",
		Economy:    40,
		Diplomacy:  20,
		Government: 20,
		Society:    20,
	},
	{
		Name:       "Capitalist Fascism",
		Economy:    20,
		Diplomacy:  20,
		Government: 20,
		Society:    20,
	},
	{
		Name:       "Conservatism",
		Economy:    30,
		Diplomacy:  40,
		Government: 40,
		Society:    20,
	},
	{
		Name:       "Neo-Liberalism",
		Economy:    30,
		Diplomacy:  40,
		Government: 40,
		Society:    20,
	},
	{
		Name:       "Classical Liberalism",
		Economy:    30,
		Diplomacy:  60,
		Government: 60,
		Society:    80,
	},
	{
		Name:       "Authoritarian Capitalism",
		Economy:    20,
		Diplomacy:  30,
		Government: 20,
		Society:    40,
	},
	{
		Name:       "State Capitalism",
		Economy:    20,
		Diplomacy:  50,
		Government: 30,
		Society:    50,
	},
	{
		Name:       "Neo-Conservatism",
		Economy:    20,
		Diplomacy:  20,
		Government: 40,
		Society:    20,
	},
	{
		Name:       "Fundamentalism",
		Economy:    20,
		Diplomacy:  30,
		Government: 30,
		Society:    5,
	},
	{
		Name:       "Libertarian Capitalism",
		Economy:    20,
		Diplomacy:  50,
		Government: 80,
		Society:    60,
	},
	{
		Name:       "Market Anarchism",
		Economy:    20,
		Diplomacy:  50,
		Government: 100,
		Society:    50,
	},
	{
		Name:       "Objectivism",
		Economy:    10,
		Diplomacy:  50,
		Government: 90,
		Society:    40,
	},
	{
		Name:       "Ultra-Capitalism",
		Economy:    0,
		Diplomacy:  40,
		Government: 50,
		Society:    50,
	},
	{
		Name:       "Anarcho-Capitalism",
		Economy:    0,
		Diplomacy:  50,
		Government: 100,
		Society:    50,
	},
}
